routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    
    return redirect(route('loginForm'));

})->name('home');

Route::namespace('App\Http\Controllers')->group(function() {


    Route::get('login', 'AuthController@loginform')->name('loginForm');
    Route::post('login', 'AuthController@login')->name('login');
    Route::get('logout', 'AuthController@logout')->name('logout');

    Route::middleware(['admin'])->namespace('Admin')->group(function () {

        Route::resource('users', 'UserController');
        Route::get('questions/change-status', 'QuestionController@changeStatus')->name('questions.changeStatus');
        Route::resource('questions', 'QuestionController');

    });
    
    Route::middleware(['user'])->namespace('User')->group(function () {

        Route::get('user-quiz', 'QuizController@index')->name('quiz.index');
        Route::get('quiz-answer', 'QuizController@answer')->name('quiz.answer');
        Route::get('reset-quiz', 'QuizController@reset')->name('quiz.reset');
        
    });

});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    const ADMIN = 1;
    const USER = 2;

    protected $appends = [

        'total_answred',
        'total_correct'

    ];

    /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $guarded = ['id'];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function isAdmin()
    {
        return $this->role_id == Self::ADMIN;
    }

    public function isUser()
    {
        return $this->role_id == Self::USER;
    }

    public function scopeUser($query)
    {
        return $query->where('role_id',Self::USER);
    }

    public function answers(){

        return $this->hasMany(UserAnswer::class);

    }

    public function getTotalAnsweredAttribute(){

        return $this->answers()->count();

    }

    public function getTotalCorrectAttribute(){

        return $this->answers()->where('true',1)->count();

    }


}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\User;
use Hash , Auth;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        
        $data = User::user()->paginate(10);
        return view('admin.user.index',compact('data'));

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
     public function create(Request $request)
    {
        return view('admin.user.add');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name'    => 'required|min:2',
            'email' => 'required|email|unique:users,email',
            'confirm_password' => 'required',
            'password' => 'required|min:8|same:confirm_password'
        ]);

        $data = $request->except(['_token', '_method','password']);
        $data['password'] = Hash::make($request->password);
        $data['role_id'] = User::USER;

        User::create($data);
        
        notify()->success('User Added Successfully');
        return redirect()->route('users.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {

        $data = User::find(base64_decode($id));
        return view('admin.user.edit', compact('data'));

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'name'    => 'required|min:2',
            'email' => 'required|email|unique:users,email,'.$id,
            'confirm_password' => 'nullable',
            'password' => 'nullable|min:8|same:confirm_password'
        ]);

        $user = User::find($id);
        
        $data = $request->except(['_token', '_method','password']);
        
        $data['password'] = Hash::make($request->password);

        $user->update($data);

        notify()->success('User successfuly updated');
        return redirect()->route('users.index');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {

        User::destroy(base64_decode($id));
        
        notify()->success('User deleted successfully');
        return back();
        
    }

}

app/Http/Controllers/User/QuizController.php
<?php

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Question;
use App\Models\Option;
use App\Models\UserAnswer;
use Auth;

class QuizController extends Controller
{
    public function index(){

        $data = Question::with('options')->active()->latest()->paginate(5);
        // return $data;
        return view('user.question',compact('data'));
    
    }

    public function answer(Request $request){

        if(UserAnswer::where(['user_id'=>Auth::id(),'question_id'=>$request->question_id])->exists()){

            return response()->json(['status'=>2 ,'message'=>'You already answered this']);

        }
        else{

            $option = Option::find($request->option_id);

            UserAnswer::create([
                'user_id'=>Auth::id(),
                'question_id'=>$request->question_id ,
                'option_id' => $request->option_id,
                'true'=> $option->true
            ]);

            return response()->json(['status'=> $option->true ,'message'=> $option->true ? 'Option selected is right': 'Option selected is Wrong']);

        }
    }

    public function reset(){

        UserAnswer::where(['user_id'=>Auth::id()])->delete();

        notify()->success('Quiz reset done');
        return redirect()->back();

    }


}

resources/views/user/question.blade.php
@extends('layouts.user')
@section('content')
<div class="container">
    <div class="row">
        <div class="col-lg-6">
            <h4> Quiz Questions</h4>
        </div>
        <div class="col-lg-4">
            <h6>Total Answered :- <span class="answered">{{Auth::user()->total_answered}}</span></h6>
            <h6>Total Correct :- <span class="correct">{{Auth::user()->total_correct}}</span></h6>
        </div>
        <div class="col-lg-2">
            <a href="{{route('quiz.reset')}}" class="btn btn-primary">Reset</a>
        </div> 
    </div>
    <div class="row">   
        @foreach($data as $key => $val)
            <h6 class="mt-4"> Question : {{$key + $data->firstItem() }} </h6>
            <div class="card">
                <div class="card-header"><strong>Q : </strong> {{$val->question}}</div>
                <div class="card-body">
                    <form action="">    
                    @foreach($val->options as $keyy => $vall)
                        <div class="form-check mt-2 mb-2">
                            <input type="radio" class="form-check-input answer" id="radio{{$val->id}}{{$vall->id}}" 
                            name="optradio{{$val->id}}" question="{{$val->id}}" value="{{$vall->id}}" {{$vall->answered == 1 ? 'checked':''}}>
                            <label class="form-check-label" for="radio{{$val->id}}{{$vall->id}}">{{$vall->option}}</label>
                        </div>
                    @endforeach
                    </form>
                </div>
                <div class="card-footer">Result :- 
                    @if($val->answered == 1)
                        @if($val->my_answer == 1)
                        <span class="result"><strong style="color:green"> True </strong></span>
                        @else
                        <span class="result"><strong style="color:red"> False </strong></span>
                        @endif
                    @else
                        <span class="result"> No answer</span>
                    @endif
                </div>
            </div>
        @endforeach
    </div>
    <div class="row mt-2">
        {!! $data->links() !!}
    </div>
</div>
@endsection
@section('extra-scripts')
<script>
    var  ajaxRequest = null;

    $('.answer').on('click', function(event) {

        event.preventDefault();

        $.ajaxSetup({cache: false});
        if (ajaxRequest != null) {
            ajaxRequest.abort();
            ajaxRequest = null;
        }   

        var option_id = $(this).val();
        var question_id = $(this).attr('question');
        
         ajaxRequest = $.ajax({
            url: "{{ route('quiz.answer') }}",
            type: 'get',
            context: this,
            data: {
                'option_id': option_id,
                'question_id': question_id,
            },
            success: function(data) {

                if(data.status == 1){
                    toastr.success(data.message)   
                    $(this).prop("checked", true);
                    $(this).parent().parent().parent().next().children('.result').html(' <strong style="color:green"> True </strong>')
                    $('.answered').html(parseInt($('.answered').html())+1);
                    $('.correct').html(parseInt($('.correct').html())+1);
                }
                else if(data.status == 2){
                    toastr.warning(data.message)
                }
                else{
                    toastr.warning(data.message)
                    $(this).prop("checked", true);
                    $(this).parent().parent().parent().next().children('.result').html(' <strong style="color:red"> False </strong>')
                    $('.answered').html(parseInt($('.answered').html())+1);
                }

                ajaxRequest = null
            },
        });
    });
</script>

@endsection