routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    
    return redirect(route('loginForm'));

})->name('home');

Route::namespace('App\Http\Controllers')->group(function() {


    Route::get('login', 'AuthController@loginform')->name('loginForm');
    Route::post('login', 'AuthController@login')->name('login');
    Route::get('logout', 'AuthController@logout')->name('logout');

    Route::middleware(['admin'])->namespace('Admin')->group(function () {

        Route::resource('users', 'UserController');
        Route::get('questions/change-status', 'QuestionController@changeStatus')->name('questions.changeStatus');
        Route::resource('questions', 'QuestionController');

    });
    
    Route::middleware(['user'])->namespace('User')->group(function () {

        Route::get('user-quiz', 'QuizController@index')->name('quiz.index');
        Route::get('quiz-answer', 'QuizController@answer')->name('quiz.answer');
        Route::get('reset-quiz', 'QuizController@reset')->name('quiz.reset');
        
    });

});

resources/views/includes/navbar.blade.php
<!-- A grey horizontal navbar that becomes vertical on small screens -->
<nav class="navbar navbar-expand-sm bg-dark navbar-dark fixed-top">
  <div class="container justify-content-center">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link {{ request()->segment(1) == 'users' ?'active':''}}" href="{{route('users.index')}}">Manage Users</a>
      </li>
      <li class="nav-item">
        <a class="nav-link {{ request()->segment(1) == 'questions' ?'active':''}}" href="{{route('questions.index')}}">Manage Questions</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{{route('logout')}}">Logout</a>
      </li>
    </ul>
  </div>
</nav>

resources/views/includes/userNav.blade.php
<!-- A grey horizontal navbar that becomes vertical on small screens -->
<nav class="navbar navbar-expand-sm bg-dark navbar-dark fixed-top mb-5">
  <div class="container">
    <ul class="navbar-nav" style="display: contents">
        <li class="nav-item">
            <a class="nav-link {{ request()->segment(1) == 'user-quiz' ?'active':''}}" href="{{route('quiz.index')}}">Quiz</a>
        </li>
        <li class="nav-item m-2 ">
            <h6 style="color:white">Total Questions:- {{$totalQuestions}} </h6>   
        </li>
        <li class="nav-item ">
            <a class="nav-link" href="{{route('logout')}}">Logout</a>
        </li>
    </ul>
  </div>
</nav>