routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    
    return redirect(route('loginForm'));

})->name('home');

Route::namespace('App\Http\Controllers')->group(function() {


    Route::get('login', 'AuthController@loginform')->name('loginForm');
    Route::post('login', 'AuthController@login')->name('login');
    Route::get('logout', 'AuthController@logout')->name('logout');

    Route::middleware(['admin'])->namespace('Admin')->group(function () {

        Route::resource('users', 'UserController');
        Route::get('questions/change-status', 'QuestionController@changeStatus')->name('questions.changeStatus');
        Route::resource('questions', 'QuestionController');

    });
    
    Route::middleware(['user'])->namespace('User')->group(function () {

        Route::get('user-quiz', 'QuizController@index')->name('quiz.index');
        Route::get('quiz-answer', 'QuizController@answer')->name('quiz.answer');
        Route::get('reset-quiz', 'QuizController@reset')->name('quiz.reset');
        
    });

});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    const ADMIN = 1;
    const USER = 2;

    protected $appends = [

        'total_answred',
        'total_correct'

    ];

    /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $guarded = ['id'];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function isAdmin()
    {
        return $this->role_id == Self::ADMIN;
    }

    public function isUser()
    {
        return $this->role_id == Self::USER;
    }

    public function scopeUser($query)
    {
        return $query->where('role_id',Self::USER);
    }

    public function answers(){

        return $this->hasMany(UserAnswer::class);

    }

    public function getTotalAnsweredAttribute(){

        return $this->answers()->count();

    }

    public function getTotalCorrectAttribute(){

        return $this->answers()->where('true',1)->count();

    }


}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\User;
use Hash , Auth;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        
        $data = User::user()->paginate(10);
        return view('admin.user.index',compact('data'));

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
     public function create(Request $request)
    {
        return view('admin.user.add');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name'    => 'required|min:2',
            'email' => 'required|email|unique:users,email',
            'confirm_password' => 'required',
            'password' => 'required|min:8|same:confirm_password'
        ]);

        $data = $request->except(['_token', '_method','password']);
        $data['password'] = Hash::make($request->password);
        $data['role_id'] = User::USER;

        User::create($data);
        
        notify()->success('User Added Successfully');
        return redirect()->route('users.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {

        $data = User::find(base64_decode($id));
        return view('admin.user.edit', compact('data'));

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'name'    => 'required|min:2',
            'email' => 'required|email|unique:users,email,'.$id,
            'confirm_password' => 'nullable',
            'password' => 'nullable|min:8|same:confirm_password'
        ]);

        $user = User::find($id);
        
        $data = $request->except(['_token', '_method','password']);
        
        $data['password'] = Hash::make($request->password);

        $user->update($data);

        notify()->success('User successfuly updated');
        return redirect()->route('users.index');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {

        User::destroy(base64_decode($id));
        
        notify()->success('User deleted successfully');
        return back();
        
    }

}

app/Http/Controllers/User/QuizController.php
<?php

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Question;
use App\Models\Option;
use App\Models\UserAnswer;
use Auth;

class QuizController extends Controller
{
    public function index(){

        $data = Question::with('options')->active()->latest()->paginate(5);
        // return $data;
        return view('user.question',compact('data'));
    
    }

    public function answer(Request $request){

        if(UserAnswer::where(['user_id'=>Auth::id(),'question_id'=>$request->question_id])->exists()){

            return response()->json(['status'=>2 ,'message'=>'You already answered this']);

        }
        else{

            $option = Option::find($request->option_id);

            UserAnswer::create([
                'user_id'=>Auth::id(),
                'question_id'=>$request->question_id ,
                'option_id' => $request->option_id,
                'true'=> $option->true
            ]);

            return response()->json(['status'=> $option->true ,'message'=> $option->true ? 'Option selected is right': 'Option selected is Wrong']);

        }
    }

    public function reset(){

        UserAnswer::where(['user_id'=>Auth::id()])->delete();

        notify()->success('Quiz reset done');
        return redirect()->back();

    }


}

resources/views/admin/user/add.blade.php
@extends('layouts.admin')
@section('content')
<div class="container">
    <div class="row">
        <div class="col-lg-10">
            <h5>Add User</h5>
        </div>
        <div class="col-lg-2">
            <a href="{{route('users.index')}}" class="btn btn-primary">Back</a>
        </div>
    </div>
    <div class="row">
        <form method="POST" action="{{route('users.store')}}">
            @csrf
            <div class="mb-3 mt-3">
                <label for="email" class="form-label">Name:</label>
                <input type="text" class="form-control" required id="email" placeholder="Enter Name" value="{{old('name')}}" name="name">
            </div>   
            @error('name')
                <span class="validation invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
            @enderror 
            <div class="mb-3 mt-3">
                <label for="email" class="form-label">Email:</label>
                <input type="email" class="form-control" required id="email" placeholder="Enter email" name="email" value="{{old('email')}}">
            </div>
            @error('email')
                <span class="validation invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
            @enderror 
            <div class="mb-3">
                <label for="pwd" class="form-label">Password:</label>
                <input type="password" class="form-control"  required id="pwd" placeholder="Enter password" name="password">
            </div>
            @error('password')
                <span class="validation invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
            @enderror
            <div class="mb-3">
                <label for="pwd" class="form-label">Confirm Password:</label>
                <input type="password" class="form-control"  required id="pwd" placeholder="Confirm password" name="confirm_password">
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
</div>
@endsection

resources/views/admin/user/edit.blade.php
@extends('layouts.admin')
@section('content')
<div class="container">
    <div class="row">
        <div class="col-lg-10">
            <h5>Edit User</h5>
        </div>
        <div class="col-lg-2">
            <a href="{{route('users.index')}}" class="btn btn-primary">Back</a>
        </div>
    </div>
    <div class="row">
        <form method="POST" action="{{route('users.update',$data->id)}}">
            @csrf
            @method('PUT')
            <div class="mb-3 mt-3">
                <label for="email" class="form-label">Name:</label>
                <input type="text" class="form-control" required id="email" placeholder="Enter Name" value="{{old('name',$data->name)}}" name="name">
            </div>   
            @error('name')
                <span class="validation invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
            @enderror 
            <div class="mb-3 mt-3">
                <label for="email" class="form-label">Email:</label>
                <input type="email" class="form-control" required id="email" placeholder="Enter email" name="email" value="{{old('email',$data->email)}}">
            </div>
            @error('email')
                <span class="validation invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
            @enderror 
            <div class="mb-3">
                <label for="pwd" class="form-label">Password:</label>
                <input type="password" class="form-control"   id="pwd" placeholder="Enter password" name="password">
            </div>
            @error('password')
                <span class="validation invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
            @enderror
            <div class="mb-3">
                <label for="pwd" class="form-label">Confirm Password:</label>
                <input type="password" class="form-control"   id="pwd" placeholder="Confirm password" name="confirm_password">
            </div>
            <button type="submit" class="btn btn-primary">Update</button>
        </form>
    </div>
</div>
@endsection

resources/views/admin/user/index.blade.php
@extends('layouts.admin')
@section('content')
<div class="container">
    <div class="row">
        <div class="col-lg-10">
            <h5>Users</h5>
        </div>
        <div class="col-lg-2">
            <a href="{{route('users.create')}}" class="btn btn-primary">Add User</a>
        </div>
    </div>
    <div class="row">
        <table class="table table-light table-striped">
            <thead>
            <tr>
                <th>Name</th>
                <th>Email</th>
                <th>Created at</th>
                <th>Action</th>
            </tr>
            </thead>
            <tbody>
                @forelse($data as $val)
                <tr>
                    <td>{{$val->name}}</td>
                    <td>{{$val->email}}</td>
                    <td>{{$val->created_at}}</td>
                    <td>
                        <a href="{{ route('users.edit', [base64_encode($val->id)]) }}"
                            class="btn btn-primary btn-sm">Edit</a>
                        <a href="javascript:void(0)" class="btn btn-danger btn-sm delete-confirm"
                            data-form="deleteForm-{{ $val->id }}">Delete</a>
                        <form id="deleteForm-{{ $val->id }}"
                            action="{{ route('users.destroy', [base64_encode($val->id)]) }}" method="post">
                            @csrf @method('DELETE')
                        </form>
                    </td>  
                </tr>
                @empty
                <tr>
                    <td colspan="4">No users</td>
                </tr>
                @endforelse
            </tbody>
        </table>
    </div>
    <div class="row">
        {!! $data->links() !!}
    </div>
</div>
@endsection