routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    
    return redirect(route('loginForm'));

})->name('home');

Route::namespace('App\Http\Controllers')->group(function() {


    Route::get('login', 'AuthController@loginform')->name('loginForm');
    Route::post('login', 'AuthController@login')->name('login');
    Route::get('logout', 'AuthController@logout')->name('logout');

    Route::middleware(['admin'])->namespace('Admin')->group(function () {

        Route::resource('users', 'UserController');
        Route::get('questions/change-status', 'QuestionController@changeStatus')->name('questions.changeStatus');
        Route::resource('questions', 'QuestionController');

    });
    
    Route::middleware(['user'])->namespace('User')->group(function () {

        Route::get('user-quiz', 'QuizController@index')->name('quiz.index');
        Route::get('quiz-answer', 'QuizController@answer')->name('quiz.answer');
        Route::get('reset-quiz', 'QuizController@reset')->name('quiz.reset');
        
    });

});

app/Models/Question.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Auth;

class Question extends Model
{
    use HasFactory;

    protected $appends = ['my_answer','answered'];

    protected $guarded = ['id'];

    public function options(){

        return $this->hasMany(Option::class);
    
    }   

    public function scopeActive($query)
    {
        return $query->where('active',1);
    }

    public function getAnsweredAttribute(){

        return UserAnswer::where(['question_id' => $this->id,'user_id' => Auth::id()])->exists() ? 1 : 0 ;
        
    }

    public function getMyAnswerAttribute(){

        $myanswer = UserAnswer::where(['question_id' => $this->id,'user_id' => Auth::id()])->first();
        
        if($myanswer){
            return $myanswer->true;
        }
        else{
            return 0;
        }
        
    }
     
}

app/Http/Controllers/Admin/QuestionController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Question;
use App\Models\Option;
use Hash , Auth;

class QuestionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        
        $data = Question::paginate(10);
        return view('admin.question.index',compact('data'));

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
     public function create(Request $request)
    {
        return view('admin.question.add');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'question'    => 'required|min:5|unique:questions,question',
            'options' => 'required',
            'correct_option' => 'required'
        ]);

        // return $request->all();

        $data = $request->except(['_token', '_method','option']);
        $data['active'] = 1;
        $question = Question::create($data);
        
        foreach($request->options as $key => $val){

            $option['question_id'] = $question->id;
            $option['option'] = $val;
            $option['true'] = $key == $request->correct_option ? '1' : '0';
            Option::create($option);

        }

        notify()->success('Question Added Successfully');
        return redirect()->route('questions.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {

        $data = Question::with('options')->find(base64_decode($id));
        // return $data;
        return view('admin.question.edit', compact('data'));

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

        $request->validate([
            'question'    => 'required|min:5|unique:questions,question,'.$id,
            'options' => 'required',
            'correct_option' => 'required'
        ]);

       
        $data = $request->except(['_token', '_method','option']);

        $question = Question::find($id);
        $question->update($data);

        foreach($request->options as $key=>$val){

            Option::where(['question_id'=> $id, 'id'=> $val['id']])->update([
                'option' => $val['value'],
                'true' => $key == $request->correct_option ? '1' : '0'
            ]);

        }

        notify()->success('Question successfuly updated');
        return redirect()->back();

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {

        Question::destroy(base64_decode($id));        
        Option::where('question_id',$id)->delete();

        notify()->success('User deleted successfully');
        return back();
        
    }

    public function changeStatus(Request $request)
    {
        
        $question = Question::find($request->id);
        $question->active = $request->status;
        $question->save();
        return $question->active;
    }
}

resources/views/admin/question/add.blade.php
@extends('layouts.admin')
@section('content')
<div class="container">
    <div class="row">
        <div class="col-lg-10">
            <h5>Add Question</h5>
        </div>
        <div class="col-lg-2">
            <a href="{{route('questions.index')}}" class="btn btn-primary">Back</a>
        </div>
    </div>
    <div class="row">
        <form method="POST" action="{{route('questions.store')}}">
            @csrf
            <div class="mb-3 mt-3">
                <label for="email" class="form-label">Question:</label>
                <input type="text" class="form-control" required id="email" placeholder="Enter Question" value="{{old('qurestion')}}" name="question">
            </div>   
            @error('question')
                <span class="validation invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
            @enderror 
            <div class="mb-3 mt-3">
                <label for="option" class="form-label">Option 1:</label>
                <input type="text" class="form-control" required id="" placeholder="Enter Option 1" name="options[1]" value="{{old('options.1')}}">
            </div>
            <div class="mb-3 mt-3">
                <label for="option" class="form-label">Option 2:</label>
                <input type="text" class="form-control" required id="" placeholder="Enter Option 2" name="options[2]" value="{{old('options.2')}}">
            </div>
            <div class="mb-3 mt-3">
                <label for="option" class="form-label">Option 3:</label>
                <input type="text" class="form-control" required id="" placeholder="Enter Option 3" name="options[3]" value="{{old('options.3')}}">
            </div>
            <div class="mb-3 mt-3">
                <label for="option" class="form-label">Option 4:</label>
                <input type="text" class="form-control" required id="" placeholder="Enter Option 4" name="options[4]" value="{{old('options.4')}}">
            </div>

            <div class="mb-3 mt-3">
                <label for="option" class="form-label">Correct Option:</label>
                <select class="form-select" required name="correct_option">
                    <option value=''>Select one...</option>  
                    <option value='1' {{old('correct_option') == '1' ? 'selected': ''}}>1</option>
                    <option value='2' {{old('correct_option') == '2' ? 'selected': ''}}>2</option>
                    <option value='3' {{old('correct_option') == '3' ? 'selected': ''}}>3</option>
                    <option value='4' {{old('correct_option') == '4' ? 'selected': ''}}>4</option>
                </select>
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
</div>
@endsection

resources/views/admin/question/edit.blade.php
@extends('layouts.admin')
@section('content')
<div class="container">
    <div class="row">
        <div class="col-lg-10">
            <h5>Edit Question</h5>
        </div>
        <div class="col-lg-2">
            <a href="{{route('questions.index')}}" class="btn btn-primary">Back</a>
        </div>
    </div>
    <div class="row">
        <form method="POST" action="{{route('questions.update',$data->id)}}">
            @csrf
            @method('PUT')
            <div class="mb-3 mt-3">
                <label for="email" class="form-label">Question:</label>
                <input type="text" class="form-control" required id="email" placeholder="Enter Question" value="{{old('question',$data->question)}}" name="question">
            </div>   
            @error('question')
                <span class="validation invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
            @enderror 

            @foreach($data->options as $key => $val)
            <div class="mb-3 mt-3">
                <label for="option" class="form-label">Option {{$key+1}}:</label>
                <input type="hidden" name="options[{{$key+1}}][id]" value="{{$val->id}}" >
                <input type="text" class="form-control" required id="" placeholder="Enter Option {{$key+1}}" name="options[{{$key+1}}][value]" value="{{old('options.$key+1.value',$val->option)}}">
            </div>
            @endforeach
            <div class="mb-3 mt-3">
                <label for="option" class="form-label">Correct Option:</label>
                <select class="form-select" required name="correct_option">
                    <option value=''>Select one...</option>  
                    <option value='1' {{old('correct_option') == '1' || $data->correct_option == 1 ? 'selected': ''}}>1</option>
                    <option value='2' {{old('correct_option') == '2' || $data->correct_option == 2 ? 'selected': ''}}>2</option>
                    <option value='3' {{old('correct_option') == '3' || $data->correct_option == 3 ? 'selected': ''}}>3</option>
                    <option value='4' {{old('correct_option') == '4' || $data->correct_option == 4 ? 'selected': ''}}>4</option>
                </select>
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
</div>
@endsection

resources/views/admin/question/index.blade.php
@extends('layouts.admin')
@section('content')
<div class="container">
    <div class="row">
        <div class="col-lg-10">
            <h5>Questions</h5>
        </div>
        <div class="col-lg-2">
            <a href="{{route('questions.create')}}" class="btn btn-primary">Add Question</a>
        </div>
    </div>
    <div class="row">
        <table class="table table-light table-striped">
            <thead>
            <tr>
                <th>Question</th>
                <th>Active</th>
                <th>Created at</th>
                <th>Action</th>
            </tr>
            </thead>
            <tbody>
                @forelse($data as $val)
                <tr>
                    <td>{{$val->question}}</td>
                    <td>
                        <input type="button" val-id="{{ $val->id }}" status="{{ $val->active ? 0 : 1 }}"
                            value="{{ $val->active ? 'Active' : 'Inactive' }}"
                            class="changeStatus text-white btn btn-{{ $val->active ? 'success' : 'warning' }} btn-sm">
                    </td>
                    <td>{{$val->created_at}}</td>
                    <td>
                        <a href="{{ route('questions.edit', [base64_encode($val->id)]) }}"
                            class="btn btn-primary btn-sm">Edit</a>
                        <a href="javascript:void(0)" class="btn btn-danger btn-sm delete-confirm"
                            data-form="deleteForm-{{ $val->id }}">Delete</a>
                        <form id="deleteForm-{{ $val->id }}"
                            action="{{ route('questions.destroy', [base64_encode($val->id)]) }}" method="post">
                            @csrf @method('DELETE')
                        </form>
                    </td>  
                </tr>
                @empty
                <tr>
                    <td colspan="4">No Questions</td>
                </tr>
                @endforelse
            </tbody>
        </table>
    </div>
    <div class="row">
        {!! $data->links() !!}
    </div>
</div>
@endsection
@section('extra-scripts')
<script>
    $('.changeStatus').on('click', function(event) {
        event.preventDefault();
        var val_id = $(this).attr('val-id');
        var status = $(this).attr('status');
        var message = "Are you sure you would like to change status of this Question";
        swal({
        title: message,
        icon: 'warning',
        buttons: ["Cancel", "Yes"],
        }).then(function(value) {

            console.log(value);

            if (value == true) {
                $.ajax({
                    url: "{{ route('questions.changeStatus') }}",
                    type: 'get',
                    data: {
                        'id': val_id,
                        'status': status,
                    },
                    success: function(id) {

                        console.log(id);
                        swal({
                            title: 'Success',
                            text: 'This question status has been changed successfully',
                            icon: '',
                        }).then(function() {
                            location.reload();
                        });
                    },
                })
            } else {
             
            }
        });
    });
</script>
@endsection